#pragma once

#include "common.h"
#include "vm.h"

typedef RValue (*BuiltinFunc)(VMContext* ctx, RValue* args, int32_t argCount);

// ===[ Built-in Variable ID Enum ]===
typedef enum {
    BUILTIN_VAR_UNKNOWN = -1,

    // Instance properties
    BUILTIN_VAR_X,
    BUILTIN_VAR_Y,
    BUILTIN_VAR_XPREVIOUS,
    BUILTIN_VAR_YPREVIOUS,
    BUILTIN_VAR_XSTART,
    BUILTIN_VAR_YSTART,
    BUILTIN_VAR_IMAGE_SPEED,
    BUILTIN_VAR_IMAGE_INDEX,
    BUILTIN_VAR_IMAGE_XSCALE,
    BUILTIN_VAR_IMAGE_YSCALE,
    BUILTIN_VAR_IMAGE_ANGLE,
    BUILTIN_VAR_IMAGE_ALPHA,
    BUILTIN_VAR_IMAGE_BLEND,
    BUILTIN_VAR_IMAGE_NUMBER,
    BUILTIN_VAR_SPRITE_INDEX,
    BUILTIN_VAR_SPRITE_WIDTH,
    BUILTIN_VAR_SPRITE_HEIGHT,
    BUILTIN_VAR_BBOX_LEFT,
    BUILTIN_VAR_BBOX_RIGHT,
    BUILTIN_VAR_BBOX_TOP,
    BUILTIN_VAR_BBOX_BOTTOM,
    BUILTIN_VAR_VISIBLE,
    BUILTIN_VAR_DEPTH,
    BUILTIN_VAR_PERSISTENT,
    BUILTIN_VAR_SOLID,
    BUILTIN_VAR_MASK_INDEX,
    BUILTIN_VAR_ID,
    BUILTIN_VAR_OBJECT_INDEX,
    BUILTIN_VAR_SPEED,
    BUILTIN_VAR_DIRECTION,
    BUILTIN_VAR_HSPEED,
    BUILTIN_VAR_VSPEED,
    BUILTIN_VAR_FRICTION,
    BUILTIN_VAR_GRAVITY,
    BUILTIN_VAR_GRAVITY_DIRECTION,
    BUILTIN_VAR_ALARM,

    // Path instance variables
    BUILTIN_VAR_PATH_INDEX,
    BUILTIN_VAR_PATH_POSITION,
    BUILTIN_VAR_PATH_POSITIONPREVIOUS,
    BUILTIN_VAR_PATH_SPEED,
    BUILTIN_VAR_PATH_SCALE,
    BUILTIN_VAR_PATH_ORIENTATION,
    BUILTIN_VAR_PATH_ENDACTION,

    // Room properties
    BUILTIN_VAR_ROOM,
    BUILTIN_VAR_ROOM_SPEED,
    BUILTIN_VAR_ROOM_WIDTH,
    BUILTIN_VAR_ROOM_HEIGHT,
    BUILTIN_VAR_ROOM_PERSISTENT,

    // View properties
    BUILTIN_VAR_VIEW_CURRENT,
    BUILTIN_VAR_VIEW_XVIEW,
    BUILTIN_VAR_VIEW_YVIEW,
    BUILTIN_VAR_VIEW_WVIEW,
    BUILTIN_VAR_VIEW_HVIEW,
    BUILTIN_VAR_VIEW_XPORT,
    BUILTIN_VAR_VIEW_YPORT,
    BUILTIN_VAR_VIEW_WPORT,
    BUILTIN_VAR_VIEW_HPORT,
    BUILTIN_VAR_VIEW_VISIBLE,
    BUILTIN_VAR_VIEW_ANGLE,
    BUILTIN_VAR_VIEW_HBORDER,
    BUILTIN_VAR_VIEW_VBORDER,
    BUILTIN_VAR_VIEW_OBJECT,
    BUILTIN_VAR_VIEW_HSPEED,
    BUILTIN_VAR_VIEW_VSPEED,

    // Background properties
    BUILTIN_VAR_BACKGROUND_VISIBLE,
    BUILTIN_VAR_BACKGROUND_INDEX,
    BUILTIN_VAR_BACKGROUND_X,
    BUILTIN_VAR_BACKGROUND_Y,
    BUILTIN_VAR_BACKGROUND_HSPEED,
    BUILTIN_VAR_BACKGROUND_VSPEED,
    BUILTIN_VAR_BACKGROUND_WIDTH,
    BUILTIN_VAR_BACKGROUND_HEIGHT,
    BUILTIN_VAR_BACKGROUND_ALPHA,
    BUILTIN_VAR_BACKGROUND_COLOR,
    BUILTIN_VAR_BACKGROUND_COLOUR,

    // OS constants
    BUILTIN_VAR_OS_TYPE,
    BUILTIN_VAR_OS_WINDOWS,
    BUILTIN_VAR_OS_PS4,
    BUILTIN_VAR_OS_PSVITA,
    BUILTIN_VAR_OS_3DS,
    BUILTIN_VAR_OS_SWITCH,

    // Timing
    BUILTIN_VAR_CURRENT_TIME,

    // File system
    BUILTIN_VAR_WORKING_DIRECTORY,

    // Arguments
    BUILTIN_VAR_ARGUMENT_COUNT,
    BUILTIN_VAR_ARGUMENT,
    BUILTIN_VAR_ARGUMENT0,
    BUILTIN_VAR_ARGUMENT1,
    BUILTIN_VAR_ARGUMENT2,
    BUILTIN_VAR_ARGUMENT3,
    BUILTIN_VAR_ARGUMENT4,
    BUILTIN_VAR_ARGUMENT5,
    BUILTIN_VAR_ARGUMENT6,
    BUILTIN_VAR_ARGUMENT7,
    BUILTIN_VAR_ARGUMENT8,
    BUILTIN_VAR_ARGUMENT9,
    BUILTIN_VAR_ARGUMENT10,
    BUILTIN_VAR_ARGUMENT11,
    BUILTIN_VAR_ARGUMENT12,
    BUILTIN_VAR_ARGUMENT13,
    BUILTIN_VAR_ARGUMENT14,
    BUILTIN_VAR_ARGUMENT15,

    // Keyboard
    BUILTIN_VAR_KEYBOARD_KEY,
    BUILTIN_VAR_KEYBOARD_LASTKEY,

    // Surfaces
    BUILTIN_VAR_APPLICATION_SURFACE,

    // Constants
    BUILTIN_VAR_TRUE,
    BUILTIN_VAR_FALSE,
    BUILTIN_VAR_PI,
    BUILTIN_VAR_UNDEFINED,

    // Path action constants
    BUILTIN_VAR_PATH_ACTION_STOP,
    BUILTIN_VAR_PATH_ACTION_RESTART,
    BUILTIN_VAR_PATH_ACTION_CONTINUE,
    BUILTIN_VAR_PATH_ACTION_REVERSE,

    // Other
    BUILTIN_VAR_FPS,
} BuiltinVarId;

void VMBuiltins_registerAll(bool isGMS2);
void VMBuiltins_free(void);
BuiltinFunc VMBuiltins_find(const char* name);
int16_t VMBuiltins_resolveBuiltinVarId(const char* name);
RValue VMBuiltins_getVariable(VMContext* ctx, int16_t builtinVarId, const char* name, int32_t arrayIndex);
void VMBuiltins_setVariable(VMContext* ctx, int16_t builtinVarId, const char* name, RValue val, int32_t arrayIndex);
